### ISSUE TITLE
New suggestions for porting

### ISSUE THREAD

**Issue by rhysperry111** [sonph/onehalf#53]
I suggest a port for Atom

**Comment by sonph** [comment]
It’s been a loooong time since I last used Atom, but I think it was using this one https://atom.io/themes/one-light-syntax. It’s what this theme is actually based on. I don’t remember exactly what are the differences, but why don’t you give it a try.

I also recommend using the spacegray light (which I ported) or dark theme. They’re based on Sublime Text spacegray, which is what you see in the screenshots.

light: https://atom.io/themes/spacegray-light-neue-ui
dark: https://atom.io/themes/spacegray-dark-neue-ui
